name: bogsi-ceridwen 

services:
  ceridwen-console:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      OLLAMA_CONNECTION_STR: "http://ceridwen-ollama:11434"
    depends_on: 
      - ceridwen-ollama
  
  ceridwen-ollama:
    image: ollama/ollama
    container_name: ceridwen-ollama
    ports: 
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [ gpu ]

volumes:
  ollama:
